blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/Subschema-LLC/aggregate-gtm-tag-template/security/advisories/new
    about: Please report security vulnerabilities privately.
  - name: Aggregate SDK & Server Documentation
    url: https://github.com/Subschema-LLC/aggregate
    about: For Aggregate server and SDK documentation.
